# Dock and Keyboard
defaults write com.apple.dock "autohide-delay" -float "0.05" # delay
defaults write NSGlobalDomain "ApplePressAndHoldEnabled" -bool "false" # repeats the key as long as it is held down
killall Dock
killall Finder

# Set HostName
sudo scutil --set HostName my-mac

# Install Command Line tools
xcode-select --install

# Install Rosetta
sudo softwareupdate --install-rosetta --agree-to-license

# Enable Touch ID in terminal
sudo nano /etc/pam.d/sudo_local
```
# uncomment following line to enable Touch ID for sudo
auth       sufficient     pam_tid.so
```

# Install Homebrew
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

# Install Apps from Brewfile
cd ~/.dotfiles/
brew bundle --verbose

# Add fish to allowed shells and set it as default
echo $(which fish) | sudo tee -a /etc/shells
chsh -s $(which fish)

# Remove login text shell
cd ~
touch .hushlogin

# Install stow dotfiles
cd ~/.dotfiles
stow fish
stow nvim
stow zed
stow karabiner
stow hammerspoon
stow mactop
stow ghostty

# Unstow
# stow -D packageToUnstow

# Uninstall everything NOT in your Brewfile (careful!) (Maintenence)
# cd ~/.dotfiles/
# brew bundle cleanup --force

# # Add the fonts repository
# brew tap homebrew/cask-fonts
# # Install Hack nerd edition font
# brew install font-hack-nerd-font

# OUTSIDE iMac + MacBook
# USB File Manager (amazon)
# morphy
# photomator
# pixelmator pro

# OUTSIDE MacBook
# logic pro
# native instruments
